"""Added user_role to User table

Revision ID: 96faf982f164
Revises: 
Create Date: 2025-01-01 14:51:13.303609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96faf982f164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
